---
###############################################################
# This series of tasks in this role manages the installation of
# Docker and a Docker registry.
###############################################################

- name: Use dnf config-manager to add docker repo
  command: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  #warn: false
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install Docker CE
  dnf:
    name: docker-ce
    state: installed
    update_cache: yes
    disable_gpg_check: yes

- name: Start Docker service
  service:
    name: docker
    state: started


